@Barbearia_Api_HostAddress = https://localhost:7030

### Listar clientes
GET {{Barbearia_Api_HostAddress}}/api/clientes
Accept: application/json

### Criar cliente
POST {{Barbearia_Api_HostAddress}}/api/clientes
Content-Type: application/json

{
  "nome": "Kelvin",
  "telefone": "123",
  "email": "kelvin@teste.com"
}